name-template: 'v$RESOLVED_VERSION 🎉'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '💥 Breaking Changes'
    labels:
      - 'breaking'
      - 'breaking-change'
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'maintenance'
  - title: '📚 Documentation'
    labels:
      - 'docs'
      - 'documentation'
  - title: '⬆️ Dependencies'
    labels:
      - 'dependencies'
      - 'deps'
  - title: '🔒 Security'
    labels:
      - 'security'
  - title: '⚡ Performance'
    labels:
      - 'performance'
      - 'perf'
  - title: '🎨 Styling'
    labels:
      - 'style'
      - 'ui'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # Zorg dat Markdown karakters goed worden weergegeven

template: |
  ## 🎉 Release v$RESOLVED_VERSION
  
  $CHANGES
  
  ## 📦 Binary Information
  - 🏷️ Version: `$RESOLVED_VERSION`
  - 🔍 Commit: `$COMMIT`
  
  ## 🚀 Installation
  1. 📥 Download the binary for your platform
  2. ▶️ Run the executable
  
  ## 📚 Documentation
  - 📖 [README](./README.md)
  - 📋 [Full Changelog](./CHANGELOG.md)
  
  ## 🙏 Thank You
  Thanks to all contributors who made this release possible!

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION