on:
  push:
    branches:
      - master

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: master
          default_bump: patch
          tag_prefix: v
          commit_message_pattern: "^(feat|fix|chore|refactor|docs|style|perf|test|build|ci|revert)(\\([\\w\\s-]*\\))?:"
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "^feat:"
          patch_pattern: "^fix:"