name: Bump version and push tag

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          fetch-depth: 0
          fetch-tags: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: master
          default_bump: patch
          tag_prefix: v
          custom_release_rules: feat:minor,fix:patch